language: python
python:
  - "3.3"

before_script:
  - psql -c 'create database dataview;' -U postgres
  - psql -U postgres -c "create extension postgis"
  
install: 
  -  pip install -r requirements.txt
  -  cp dataview/settings.dist.py dataview/settings.py
  -  sed -i "s/SECRET_KEY = ''/SECRET_KEY = '`python -c 'import random; print(\"\".join([random.SystemRandom().choice(\"abcdefghijklmnopqrstuvwxyz0123456789@#$%^&*(-_=+)\") for i in range(50)]))'`'/" dataview/settings.py 
script: 
  python manage.py test