language: python
python:
  - "3.5"

before_script:
  - psql -c 'create database dataview;' -U postgres
  
before_install:
  - sudo apt-get install postgresql-9.5-postgis-2.3

install: 
  -  pip install -r requirements.txt
  -  cp dataview/settings.dist.py dataview/settings.py
  -  sed -i "s/SECRET_KEY = ''/SECRET_KEY = '`python -c 'import random; print(\"\".join([random.SystemRandom().choice(\"abcdefghijklmnopqrstuvwxyz0123456789@#$%^&*(-_=+)\") for i in range(50)]))'`'/" dataview/settings.py 
  -  python manage.py migrate
  -  python manage.py makemigrations
  -  sed -i "s/'#'guardian',/'guardian',/" dataview/settings.py
  -  python manage.py migrate

script:
  -  python manage.py test
